config/routes.rb
require 'api_contraints'

Geolocationapp::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :relative_locations, only: [:index]
    end
  end

  resources :locations do
    get "/locations" => "locations#index"
    post :import, :on => :collection
  end
  
  root to: 'home#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  include FileImporter

  #For geo computations to assume a spherical earth:
  set_rgeo_factory_for_column(:latlon,
      RGeo::Geographic.spherical_factory(:srid => 4326))
      
  validates :name, presence: true
  validates :latlon, presence: true

  def self.import(file)
    FileImporter.import_file(file.path)
  end
 
end

app/models/relative_locations.rb
class RelativeLocations
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :lat, :lon, :radius, :format, :action, :controller, :search_radius

  #more validations are required for these values (format, lenght, etc):
  validates_presence_of :lat, :lon 
  
  METERS_IN_MILES = 1609.to_s

  def initialize(attributes = {})
    @attributes = attributes
    ensure_params_have_values
    @attributes.each do |name, value|
      send("#{name}=", value)
    end
    list
  end
  
  def list
    @_relative_locations ||= Location.find(
      :all, 
      :select => "*, ST_Distance(latlon,'" + origin_point.to_s + "') / " + METERS_IN_MILES + " as distance",
      :order  => "distance asc",
      :conditions => "ST_Distance(latlon,'" + origin_point.to_s + "') < " + search_radius.to_s + "*" + METERS_IN_MILES
    )
  end
  
  def as_json(options = {})
    # optional k,v to add to the json response such as:
    # response code
    # url path to API documentation
  end
  
  def origin_point
    RGeo::Geographic.spherical_factory.point(@attributes[:lon],@attributes[:lat])
  end

  # I decided to set a default value if params are empty. The solution could be more elegant.
  def ensure_params_have_values
    @attributes[:lat] = 33.1243208 unless @attributes[:lat].present? 
    @attributes[:lon] = -117.32582479999996 unless @attributes[:lon].present? 
    @attributes[:radius].present? ? @_search_radius = @attributes[:radius] : self.set_radius
  end

  def persisted?
    false
  end  
  
  def search_radius
    @_search_radius
  end
  
  def set_radius
     @_search_radius, @attributes[:radius]  = 5, 5
  end

end

app/controllers/api/v1/relative_locations_controller.rb
module Api
  module V1
    class RelativeLocationsController < ApplicationController
      respond_to :json

      def index
        locations = RelativeLocations.new(params)
        if locations.valid?  
          render :json => locations
        else
          render :json => {:error => errors_for(locations)}, :status => :unprocessable_entity
        end
      end

      private
      
      def errors_for(object)
        object.errors.map {|k, m| "#{k} #{m}" }
      end 

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController 
  helper_method :locations, :location, :marker_set, :origin_point, :search_radius
  attr_accessor :locations, :search_radius, :origin_point
  
  def index
    @_relative_locations||= RelativeLocations.new(params)
    if @_relative_locations.valid?
      self.locations = @_relative_locations.list
      self.search_radius = @_relative_locations.search_radius
      self.origin_point = @_relative_locations.origin_point
      marker_set
    else
      # This badly needs some rescuing:
      redirect_to root_url, notice: "Something went wrong while trying to load locations."
    end
  end
  
  def import
    begin
      Location.import(params[:file])
      redirect_to locations_url, notice: "Location list imported."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format, or no file selected."
    end
  end
  
  private

  def marker_set
    @_market_set = Gmaps4rails.build_markers(locations) do |location, marker|
      marker.lat location.latlon.latitude
      marker.lng location.latlon.longitude
      marker.title location.name
    end   
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Geolocation App</h1>

<legend>Please select a file to upload</legend>

<div class=container> 
  <%= form_tag import_locations_path, multipart: true do %> 
    <div class="form-group">
      <%= file_field_tag :file %>
      <p class="help-block">Please select a tab delimited file.</p>
      <%= submit_tag "Import CSV", class: 'btn btn-primary' %>
    </div>
  <% end %>

  <br>
  <h4>You may download a small sample file:
  <%= link_to('Download','/downloads/locations.tsv') %></h4>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'Locations', locations_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Geolocationapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Geolocationapp" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= flash[:notice] %>
    <header class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <div class="container">
              <%= render 'layouts/navigation' %>
            </div>
          </nav>
        </header>
        <main role="main">
          <div class="container">
            <div class="content-body">
               <div class="row">
                <div class="span12">
                  <%= render 'layouts/messages' %>
                  <%= yield %>
                </div>
              </div>
              <footer>
              </footer>
            </div>
          </div>
        </main>
  </body>
</html>

app/views/locations/_lat_lon_input.erb
<legend>Use point of origin given or enter a new one</legend>

<form class="form-vertical" role="form">
  <div class="form-group">
    <div class="row">
      <div class="col-xs-3">
        <label for="latitudeInput">Latitude</label>
        <input type="text" class="form-control" id="latitudeInput" name="lat" value="<%= origin_point.latitude %>">
      </div>
      <div class="col-xs-3">
        <label for="longitudeInput">Longitude</label>
        <input type="text" class="form-control" id="longitudeInput" name="lon" value="<%= origin_point.longitude %>">
      </div>
      <div class="col-xs-3">
        <label for="radiusInput">Radius (miles)</label>
        <input type="text" class="form-control" id="radiusInput" name="radius" value="<%= search_radius %>">
      </div>      
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  <button type="reset" class="btn btn-default">Reset</button>
</form>
<br>
<br>

app/views/locations/_map.erb
<div style='width: 800px;'>
  <div id="map" style='width: 700px; height: 400px;'></div>
</div>

<script type="text/javascript">

handler = Gmaps.build('Google');
map_center = new google.maps.LatLng(<%= origin_point.latitude %>, <%= origin_point.longitude%> )

handler.buildMap({ 
  provider: {
    zoom: 10,
    center: map_center
  }, 
  internal: {id: 'map'}}, 
  function(){
    markers = handler.addMarkers(<%=raw marker_set.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
});
</script>

app/views/locations/index.html.erb
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<h1> Locations</h1>

<div class=container>
  <%= render 'locations/lat_lon_input' %>
  <div class="row">
    <div id="locTable" class="col-md-6">
      <%= render 'locations/map' %>
      <h4>Locations within <%= search_radius %> miles and sorted by the shortest distance from the point of origin:</h4>
      <h4><span class="label label-info">(<%= origin_point.latitude %>, <%= origin_point.longitude %>)</span></h4>
    </div>    
  </div>
  <div class="row">
    <div id="locTable" class="col-md-8">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Latitude/Longitude</th>
            <th style="text-align:right">Distance (miles)</th>
          </tr>
        </thead>
        <tbody>
          <% locations.each do |loc| %>
            <tr>
              <td><%= loc.id %></td>
              <td><%= loc.name %></td>
              <td><%= loc.latlon.latitude %>/<%= loc.latlon.longitude %></td>
              <td  class='distance'><%= loc.distance.round(2) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<h1><%= location.name %></h1>
<p>content</p>
<%= link_to "Back", locations_path %>